# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - ui

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c22a0e0e-2499-48a3-99e1-64ae0ec0fa17'
  imageRepository: 'sos'
  dockerfilePath: '$(Build.SourcesDirectory)/ui/Dockerfile'  
  tag: '$(Build.BuildId)'

steps:
  - script: |
      yarn lint
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  - task: Docker@2
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      containerRegistry: 'soscontainers'
      repository: 'sosui'
      command: 'buildAndPush'
      Dockerfile: '$(dockerfilePath)'
      tags: |
        $(tag)
        latest    

  - task: KubernetesManifest@0
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: Deploy
    inputs:
      kubernetesServiceConnection: soskube
      namespace: sos
      manifests: |
        ui/sosui.yml
      containers: |
        soscontainers.azurecr.io/sosui:$(tag)